#pragma once

enum class ButtonEvent {
    BUTTON1_PRESSED,
    BUTTON2_PRESSED,
    BUTTON3_PRESSED,
    BUTTON4_PRESSED,
    MOVEMENT_DETECTED,
    ORIENTATION_UP,
    ORIENTATION_DOWN,
    ORIENTATION_LEFT,
    ORIENTATION_RIGHT,
    ORIENTATION_TOP,
    ORIENTATION_BOTTOM,
    ORIENTATION_UNKNOWN
};